stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build donald:
  stage: build
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs
  tags:
    - donald
  script:
    - ./gradlew assemble

test donald:
  stage: test
  tags:
    - donald
  script:
    - ./gradlew check

deploy donald:
  stage: deploy
  only:
    refs:
      - master
      - feature/ci-cd
  tags:
    - donald
  script:
    - mkdir -p ~/api-deployment # mkdir make folder api-deployment ~/ is under current user directory so for gitlab it would be /home/gitlab/api-deployment
    - rm -rf ~/api-deployment/* # rm remove -rf is recursive files from api-deployment
    - cp -r build/libs/. ~/api-deployment # cp - copy build/libs is where
    - sudo systemctl restart gitlab-runner

