stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build donald:
  stage: build
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs
  tags:
    - donald
  script:
    - ./gradlew assemble

test donald:
  stage: test
  tags:
    - donald
  script:
    - ./gradlew check

deploy donald:
  stage: deploy
  only:
    refs:
      - master
  tags:
    - donald
  script:
    - mkdir -p ~/api-deployment
    - rm -rf ~/api-deployment/*
    - cp -r build/libs/. ~/api-deployment
    - sudo systemctl restart donald

deploy dev-donald:
  stage: deploy
  only:
    refs:
      - feature/*
  tags:
    - donald
  script:
    - mkdir -p ~/dev-api-deployment
    - rm -rf ~/dev-api-deployment/*
    - cp -r build/libs/. ~/dev-api-deployment
    - sudo systemctl restart donald

