version: '3'
services:
  database:
    image: postgres
    environment:
      -
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=programm
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
    - 5432:5432
