version: '3'
services:
  backend:
    image: songmeo/taltech-donald:latest
    ports:
      - 8080:8080
    depends_on:
      - "database"
    command: [ "./wait-for-it.sh", "database:5432" ]
  database:
    image: postgres
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USERNAME=$POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - pgdata:/var/lib/postgresql/data/pgdata
volumes: 
  pgdata: