server:
  servlet:
    context-path: /api
spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    #    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1 # this one is in memory
    url: jdbc:postgresql://localhost:5432/programm # this one is on the disk, notice the h2 folder and contents it creates
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    platform: POSTGRES
logging:
  file:
    path: ./logs
