server:
  servlet:
    context-path: /api
spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/programm
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    platform: POSTGRES
logging:
  file:
    path: ./logs
