server:
  servlet:
    context-path: /api
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: taltechdonalds2020@gmail.com
    password: TaltechDonalds2020
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
        from:
          email: taltechdonalds2020@gmail.com
  jackson:
    default-property-inclusion: non_null
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://database:5432/programm
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    platform: POSTGRES
logging:
  file:
    path: ./logs
jwt:
  secret: bRUG198EfyW3g7GF8yTufhKUjUbejrRKoJi3lqzZ2V3pYAzWowSTtBc7MOHix6R
  durationMin: 120

