spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults : false
    hibernate:
      ddl-auto: create
  datasource:
    #    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1 # this one is in memory
    url: jdbc:h2:./h2/heroes;AUTO_SERVER=TRUE # this one is on the disk, notice the h2 folder and contents it creates
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      #      this enables http://localhost:8080/h2-console
      enabled: true
logging:
  file:
    path: ./logs
